package logic.document.operations.format.modules

import org.jsoup.nodes.Document
import org.jsoup.nodes.Element
import util.dom.recreateWithoutNodes

object FormatEmbedModule : IHtmlFormatModule {
    override suspend fun process(document: Document): Document {
        document
            .getElementsByClass("andropov_video--iframe")
            .map { it.recreateWithoutNodes() }
            .forEach { embedVideo ->
                val iframeUrl = embedVideo.attr("data-video-iframe")

                if (iframeUrl.isNullOrEmpty()) return@forEach

                // https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page
                val iframe = Element("iframe").also {
                    it.attr("src", iframeUrl)

                    // copied from embed generated by YouTube
                    it.attr(
                        "allow",
                        "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    )
                    it.attr("allowfullscreen", "")
                    it.attr("frameborder", "0")

                    it.attr("width", "100%")
                    it.attr("height", "100%")
                    it.attr("title", "Embed video player")
                }

                embedVideo.appendChild(iframe)
            }

        return document
    }
}