name: Bug report
description: Create and send a bug report to help us improve
labels: bug
title: | 
  [BUG] *Title of issue*
body:
- type: textarea
  id: version
  attributes:
    label: Program version
    placeholder: | 
      e.g.: 1.0.3
  validations:
    required: true
- type: textarea
  id: errordesc
  attributes:
    label: Error description
    description: A clear and concise description of what the bug is.
    placeholder: |
      When pressing *this* button, program throws NullPointerReference.
    render: markdown
  validations:
    required: true
- type: textarea
  id: howto
  attributes:
    label: How to reproduce error
    description: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Scroll down to '....'
      3. Click on '....'
      4. See error
    render: markdown
  validations:
    required: true
- type: textarea
  id: expectation
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen.
    render: text
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If you can, please add screenshots to help explain your problem.
  validations:
    required: false
- type: textarea
  id: deviceinfo
  attributes:
    label: Information about the device
    placeholder: |
      OS: [e.g. Windows 10 21H2]
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other information about the problem here.
    render: markdown
  validations:
    required: false