name: Жалоба на ошибку/баг
description: Отправить отчет о ошибке
labels: bug
title: | 
  [BUG] *Заголовок баг репорта*
body:
- type: textarea
  id: version
  attributes:
    label: Версия программы
    placeholder: | 
      Например: 1.0.3
  validations:
    required: true
- type: textarea
  id: errordesc
  attributes:
    label: Описание ошибки
    description: Четкое и краткое описание ошибки.
    placeholder: |
      При нажатие на X кнопку программа вылетает.
    render: markdown
  validations:
    required: true
- type: textarea
  id: howto
  attributes:
    label: Как получить ошибку
    description: Шаги для воспроизведения ошибки
    placeholder: |
      1. Перейдите в '...'
      2. Прокрутите вниз до '....'
      3. Нажмите на '....'.
      4. Ошибка
    render: markdown
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Скриншоты
    description: Если возможно, добавьте скриншоты, чтобы помочь объяснить вашу проблему.
  validations:
    required: false
- type: textarea
  id: deviceinfo
  attributes:
    label: Логи
    description: Их можно получить в окне вылета программы или можно открыть папку в настройках и скопировать логи оттуда
    render: markdown
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Дополнительный контекст
    description: Добавьте сюда любые другие сведения о проблеме.
  validations:
    required: false
