name: Жалоба на ошибку/баг
description: Отправить отчет о ошибке
labels: bug
title: | 
  [BUG] 
body:
- type: textarea
  id: version
  attributes:
    label: Версия программы
    placeholder: | 
      Например: 1.0.3
  validations:
    required: true
- type: textarea
  id: errordesc
  attributes:
    label: Описание ошибки
    description: Четкое и краткое описание ошибки.
    placeholder: |
      При нажатие на эту кнопку появляется ошибка NullPointerReference.
    render: markdown
  validations:
    required: true
- type: textarea
  id: howto
  attributes:
    label: Как получить ошибку
    description: Шаги для воспроизведения ошибки
    placeholder: |
      1. Перейдите в '...'
      2. Прокрутите вниз до '....'
      3. Нажмите на '....'.
      4. Ошибка
    render: markdown
  validations:
    required: true
- type: textarea
  id: expectation
  attributes:
    label: Ожидаемое поведение
    description: |
      Четкое и краткое описание того, что вы ожидали, что произойдет.
    render: text
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Скриншоты
    description: Если возможно, добавьте скриншоты, чтобы помочь объяснить вашу проблему.
  validations:
    required: false
- type: textarea
  id: deviceinfo
  attributes:
    label: Сведения об устройстве
    placeholder: |
      ОС: [например, Windows 10 21H2] 
  validations:
    required: false
